//! Cross-language artifact generator.
//!
//! Reads the constants declared in `src/token.zig` via comptime reflection and
//! emits the mirrors that the tree-sitter build vendors as source files:
//!
//!   generated/constants.js   character + limit constants for the grammar JS
//!   generated/constants.h     same, as #defines for external C scanners
//!   generated/escapes.js      string-escape symbol set for the grammar JS
//!
//! These exist because a different toolchain (tree-sitter's JS + C build) needs
//! them as files; it can't read a Zig registry. Run with `zig build gen`; the
//! output directory is passed as the first argument by the build step.
//!
//! Operation/macro metadata is deliberately NOT emitted here: it is registry-
//! derived and reproducible by running the binary (`lish --dump-ops` /
//! `--dump-macros`), and Zig consumers read it straight off the registry via
//! `lish.introspect`. See src/introspect.zig.
//!
//! Reflection buckets each integer-valued `pub const` in `token.zig` by value:
//!
//!   0x20..0x7E   printable source character   emitted as a char literal
//!   0x00..0x1F   control character            skipped (escape-table domain, B5.2)
//!   >= 256       parse-time limit             emitted as a decimal number
//!
//! The gap between 0x7E and 256 keeps the two emitted buckets unambiguous: every
//! structural character lish matches in source is printable, and every limit is
//! larger than any byte value.

const std = @import("std");
const lish = @import("lish");
const token = lish.token;

const CHAR_MIN = 0x20;
const CHAR_MAX = 0x7E;
const LIMIT_MIN = 256;

const HEADER =
    \\// Generated by lish-zig/tools/gen.zig from src/token.zig.
    \\// DO NOT EDIT. Run `zig build gen` to regenerate.
    \\
;

const Constant = struct {
    name: []const u8,
    value: i128,
};

/// All integer `pub const` decls of `token.zig` whose value falls in `[lo, hi]`,
/// in source-declaration order.
fn collect(comptime lo: i128, comptime hi: i128) []const Constant {
    comptime {
        var out: []const Constant = &.{};
        for (@typeInfo(token).@"struct".decls) |decl| {
            const value = @field(token, decl.name);
            switch (@typeInfo(@TypeOf(value))) {
                .int, .comptime_int => {
                    const wide: i128 = value;
                    if (wide >= lo and wide <= hi) {
                        out = out ++ &[_]Constant{.{ .name = decl.name, .value = wide }};
                    }
                },
                else => {},
            }
        }
        return out;
    }
}

const characters = collect(CHAR_MIN, CHAR_MAX);
const limits = collect(LIMIT_MIN, std.math.maxInt(i128));

fn longestName(comptime sets: []const []const Constant) comptime_int {
    comptime {
        var max = 0;
        for (sets) |set| for (set) |c| {
            if (c.name.len > max) max = c.name.len;
        };
        return max;
    }
}

fn padding(comptime name: []const u8, comptime width: comptime_int) []const u8 {
    return " " ** (width - name.len + 1);
}

fn jsValue(comptime value: i128) []const u8 {
    if (value > CHAR_MAX) return std.fmt.comptimePrint("{d}", .{value});
    return switch (@as(u8, @intCast(value))) {
        '\'' => "\"'\"",
        '\\' => "'\\\\'",
        else => |ch| std.fmt.comptimePrint("'{c}'", .{ch}),
    };
}

fn cValue(comptime value: i128) []const u8 {
    if (value > CHAR_MAX) return std.fmt.comptimePrint("{d}", .{value});
    return switch (@as(u8, @intCast(value))) {
        '\'' => "'\\''",
        '\\' => "'\\\\'",
        else => |ch| std.fmt.comptimePrint("'{c}'", .{ch}),
    };
}

fn buildJs() []const u8 {
    comptime {
        const width = longestName(&.{ characters, limits });
        var out: []const u8 = HEADER ++ "\nmodule.exports = {\n";
        out = out ++ "    // Structural source characters.\n";
        for (characters) |c| {
            out = out ++ "    " ++ c.name ++ ":" ++ padding(c.name, width) ++ jsValue(c.value) ++ ",\n";
        }
        out = out ++ "\n    // Parse-time limits.\n";
        for (limits) |c| {
            out = out ++ "    " ++ c.name ++ ":" ++ padding(c.name, width) ++ jsValue(c.value) ++ ",\n";
        }
        return out ++ "};\n";
    }
}

fn buildC() []const u8 {
    comptime {
        const prefix = "LISH_";
        const width = longestName(&.{ characters, limits }) + prefix.len;
        var out: []const u8 = HEADER ++
            \\
            \\#ifndef LISH_TREE_SITTER_CONSTANTS_H
            \\#define LISH_TREE_SITTER_CONSTANTS_H
            \\
            \\// Structural source characters.
            \\
        ;
        for (characters) |c| {
            const name = prefix ++ c.name;
            out = out ++ "#define " ++ name ++ padding(name, width) ++ cValue(c.value) ++ "\n";
        }
        out = out ++ "\n// Parse-time limits.\n";
        for (limits) |c| {
            const name = prefix ++ c.name;
            out = out ++ "#define " ++ name ++ padding(name, width) ++ cValue(c.value) ++ "\n";
        }
        return out ++ "\n#endif\n";
    }
}

/// The single-char escape symbols `\X` that `escSymToChar` recognizes, found by
/// probing the function over the whole byte domain. The function is the source
/// of truth, so probing it can never disagree with it.
fn collectEscapeSymbols() []const u8 {
    comptime {
        var out: []const u8 = &.{};
        var symbol: u16 = 0;
        while (symbol < 256) : (symbol += 1) {
            const byte: u8 = @intCast(symbol);
            if (token.escSymToChar(byte) != null) out = out ++ &[_]u8{byte};
        }
        return out;
    }
}

fn jsonChar(comptime ch: u8) []const u8 {
    return switch (ch) {
        '\\' => "\"\\\\\"",
        '"' => "\"\\\"\"",
        else => std.fmt.comptimePrint("\"{c}\"", .{ch}),
    };
}

fn buildEscapesJs() []const u8 {
    comptime {
        var items: []const u8 = "";
        for (collectEscapeSymbols(), 0..) |symbol, i| {
            if (i != 0) items = items ++ ", ";
            items = items ++ jsonChar(symbol);
        }
        return HEADER ++
            \\
            \\module.exports = {
            \\    // Single-char escape symbols recognized after a backslash in a lish
            \\    // string literal (the `\X` forms). Probed from token.zig's escSymToChar.
            \\    SINGLE_CHAR_ESCAPES: [
        ++ items ++ "],\n};\n";
    }
}

const js_content = buildJs();
const c_content = buildC();
const escapes_content = buildEscapesJs();

pub fn main(init: std.process.Init) !void {
    const io = init.io;

    var stderr_writer = std.Io.File.stderr().writer(io, &.{});
    const stderr = &stderr_writer.interface;

    var arg_iter = init.minimal.args.iterate();
    _ = arg_iter.next(); // skip argv[0]
    const out_dir = arg_iter.next() orelse {
        try stderr.writeAll("usage: gen <output-directory>\n");
        return error.MissingOutputDirectory;
    };

    const cwd = std.Io.Dir.cwd();
    try cwd.createDirPath(io, out_dir);

    try writeInto(io, cwd, out_dir, "constants.js", js_content);
    try writeInto(io, cwd, out_dir, "constants.h", c_content);
    try writeInto(io, cwd, out_dir, "escapes.js", escapes_content);

    var stdout_writer = std.Io.File.stdout().writer(io, &.{});
    const stdout = &stdout_writer.interface;
    try stdout.print("gen: wrote constants.js, constants.h, escapes.js to {s}\n", .{out_dir});
}

fn writeInto(io: std.Io, dir: std.Io.Dir, out_dir: []const u8, name: []const u8, data: []const u8) !void {
    var path_buf: [std.fs.max_path_bytes]u8 = undefined;
    const path = try std.fmt.bufPrint(&path_buf, "{s}/{s}", .{ out_dir, name });
    try dir.writeFile(io, .{ .sub_path = path, .data = data });
}
